In [1]:
import numpy as np

In [3]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [6]:
#查看数组维数
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.dtype

dtype('int64')

In [9]:
arr1.dtype

dtype('float64')

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
np.arange(2,16,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [20]:
np.empty((2,3,2))

array([[[4.65671693e-310, 0.00000000e+000],
        [6.91621321e-310, 6.91621327e-310],
        [6.91621321e-310, 6.91619053e-310]],

       [[6.91621320e-310, 6.91619053e-310],
        [3.75282236e+233, 1.63041663e-322],
        [4.65671668e-310, 6.91621420e-310]]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
np.ones((3,4),dtype="S10")

array([[b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1']], dtype='|S10')

In [36]:
arr = np.array([
    [1,2,3],
    [4,5,6]
],dtype=np.float)

In [37]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
arr3 = np.arange(10)
arr3[1]

1

In [43]:
arr3[3:5]

array([3, 4])

In [45]:
#numpy中切片赋值都是传递引用，如果想传递值，请使用.copy()进行\

arr_slice = arr3[5:8]

In [46]:
arr_slice[1] = 1111

arr3

array([   0,    1,    2,    3,    4,    5, 1111,    7,    8,    9])

In [48]:
arr_slice2 = arr3[5:8].copy()
arr_slice2[1] = 222

arr3

array([   0,    1,    2,    3,    4,    5, 1111,    7,    8,    9])

In [51]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d[2]

array([7, 8, 9])

In [52]:
arr2d[0,2]

3

In [54]:
arr3d = np.arange(1,13).reshape((2,2,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[1,0]

array([7, 8, 9])

In [64]:
arr3d[0,:1,:2]

array([[1, 2]])

In [66]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [68]:
data2 = np.random.randn(7,4)
data2

array([[-1.22994387, -0.10905405, -0.3524669 ,  1.95872801],
       [ 0.75393201,  0.20130743, -0.3824558 , -0.97261433],
       [ 1.21470613,  0.45298468, -0.0697146 ,  0.30566693],
       [ 0.25492128, -0.5592456 ,  0.3647146 , -1.55291777],
       [-0.16312537, -0.42288093, -0.64909601, -0.98191999],
       [-0.92467566, -0.74867755,  0.80121302,  0.39772169],
       [ 0.26366948, -0.41333137, -1.9670975 , -1.06980096]])

In [69]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [70]:
data2[names == 'Bob']

array([[-1.22994387, -0.10905405, -0.3524669 ,  1.95872801],
       [ 0.25492128, -0.5592456 ,  0.3647146 , -1.55291777]])

In [71]:
data2[names == 'Bob',2:]

array([[-0.3524669 ,  1.95872801],
       [ 0.3647146 , -1.55291777]])

In [73]:
data2[~(names == 'Bob')]

array([[ 0.75393201,  0.20130743, -0.3824558 , -0.97261433],
       [ 1.21470613,  0.45298468, -0.0697146 ,  0.30566693],
       [-0.16312537, -0.42288093, -0.64909601, -0.98191999],
       [-0.92467566, -0.74867755,  0.80121302,  0.39772169],
       [ 0.26366948, -0.41333137, -1.9670975 , -1.06980096]])

In [75]:
arr4  = np.empty([8,4])

for i in range(8):
    arr4[i] = i

arr4

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [78]:
arr4[[4,3,0,-1,7]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [82]:
arr5 = np.arange(32).reshape(8,4)
arr5[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [87]:
arr5[[1,5,7,2]][:2,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22]])

In [90]:
arr6 = np.random.randn(6,3)

np.dot(arr6.T,arr6)

array([[ 6.87072087,  0.32926232,  0.42110052],
       [ 0.32926232,  4.34955474,  4.40788714],
       [ 0.42110052,  4.40788714, 13.7783199 ]])

In [95]:
arr7 = np.arange(11)
np.exp10(arr7)

AttributeError: module 'numpy' has no attribute 'exp10'

In [99]:
x = np.random.randn(8)
y = np.random.randn(8)
np.asarray([y1 if x1>y1 else x1 for x1, y1 in zip(x,y)])

array([ 0.25807829, -1.39456744, -0.88294821, -0.2965907 , -1.1966471 ,
       -0.14792101, -2.43868274, -1.06715302])

In [101]:
np.modf(x)

(array([ 0.25807829, -0.39456744,  0.61584275, -0.2965907 , -0.1966471 ,
         0.27166553, -0.43868274,  0.58626348]),
 array([ 0., -1.,  1., -0., -1.,  0., -2.,  0.]))

In [104]:
points = np.arange(-5,5,0.01)

In [105]:
xs,ys = np.meshgrid(points,points)

In [106]:
np.where([1,1,1,0,0,0,0,1],x,y)

array([ 0.25807829, -1.39456744,  1.61584275,  0.60050075,  0.06950632,
       -0.14792101, -0.06272236,  0.58626348])

In [108]:
arr8 = np.arange(16).reshape(4,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
arr8.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])

In [117]:
arr8.sum(axis = 0)

array([24, 28, 32, 36])

In [116]:
arr8.sum(0)

array([24, 28, 32, 36])

In [120]:
arr9 = np.arange(9).reshape(3,3)
np.cumprod(arr9,axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [121]:
arr9.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [135]:
arr10 = np.random.randn(9).reshape(3,3)
arr10

array([[ 0.07655949, -0.77716083,  0.2873384 ],
       [ 2.19891828,  0.08792436, -0.86375855],
       [-1.94870904, -0.46900664, -0.77242969]])

In [147]:
arr11 = np.array([1,1,1,3,2,5,5,5])

In [148]:
arr11[np.argpartition(arr11,3)]

array([1, 1, 1, 2, 3, 5, 5, 5])

In [150]:
np.argpartition(arr11,3)

array([0, 1, 2, 4, 3, 5, 6, 7])