In [1]:
import numpy as np


In [2]:
arr = np.random.randn(100)
np.array(arr>0).sum()

46

In [6]:
arr = np.random.randn(5,3)
np.sort(arr,axis=0)

array([[-0.190246  , -0.9262361 , -0.9043165 ],
       [ 0.08723888, -0.44870058, -0.51112242],
       [ 0.42962297,  0.72748266, -0.04454563],
       [ 0.71822109,  1.5912869 ,  0.25496071],
       [ 1.56464724,  2.27393988,  0.68313916]])

In [6]:
#return_index返回去重索引，return_inverse返回不去重索引
arr2 = np.array([2,2,2,1,1,1,0,0,9,9,5,5,5])
np.unique(arr2,return_index=True,return_inverse=True)

(array([0, 1, 2, 5, 9]),
 array([ 6,  3,  0, 10,  8]),
 array([2, 2, 2, 1, 1, 1, 0, 0, 4, 4, 3, 3, 3]))

In [11]:
arr3 = np.arange(10)
np.save('saveData_demo.npy',arr3)

In [12]:
np.load('saveData_demo.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr5 = np.random.randn(5,5)
np.diag(arr5)

array([ 0.76666811,  0.10843133, -1.8107568 , -0.44489876,  0.10534535])

In [15]:
np.random.normal(size=(4,4))

array([[ 0.9217185 , -0.59581405,  0.9591173 ,  1.53118584],
       [ 0.23676819,  0.48789143,  0.59268989, -0.44429713],
       [ 2.28190829, -0.07776771, -0.68660831, -0.58478344],
       [ 2.13071893, -1.01258745, -0.17970099,  0.91896268]])

In [19]:
#提前指定seed，可以得到相同的值
np.random.seed(100)

np.random.randn(4,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114]])

In [20]:
np.random.seed(100)

np.random.randn(4,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114]])

In [11]:
#随机漫步案例
draws = np.random.randint(0,2,size=1000)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()

In [12]:
walk.max()

27

In [14]:
walk.min()


-15

In [17]:
np.abs(walk>10).argmax()

406

In [19]:
#模拟多个随机漫步
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)

In [32]:
hits30 = (np.abs(walks)>=30).any(1)

In [33]:
hits30.sum()

3366