In [1]:
import numpy as np

In [15]:
arr = np.arange(10).reshape(2,5)
np.add.reduce(arr)

array([ 5,  7,  9, 11, 13])

In [16]:
arr2 = np.random.randn(5,5)
arr2[:,1:]

array([[-0.30123811, -1.26329624,  0.43035633, -2.75518706],
       [ 1.04306431, -0.94036898, -0.40047701,  1.57571607],
       [ 1.16511793, -0.66908596,  1.26565461, -0.24286242],
       [-2.04484475,  0.06133436,  1.01413701,  0.00410759],
       [ 0.43137441, -0.23686788, -0.84180627,  0.64188465]])

In [21]:
arr3 = np.arange(3).repeat([1,2,2])

(5,)

In [22]:
np.multiply.outer(arr3,np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [27]:
result = np.subtract.outer(np.arange(12).reshape(3,4),np.arange(5))

In [29]:
def add_elements(x,y):
    return x+y

add_them = np.frompyfunc(add_elements,2,1)

add_them(np.arange(8),np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [32]:
selfStructType = [('x',np.float),('y',np.int)]
selfArr = np.array([(1.5,2),(2.5,3)],dtype=selfStructType)
selfArr

array([(1.5, 2), (2.5, 3)], dtype=[('x', '<f8'), ('y', '<i8')])

In [35]:
selfStructType2 = [('x',np.float,2),('y',np.int)]
selfArr2 = np.zeros(4,dtype=selfStructType2)
selfArr2

array([([0., 0.], 0), ([0., 0.], 0), ([0., 0.], 0), ([0., 0.], 0)],
      dtype=[('x', '<f8', (2,)), ('y', '<i8')])

In [41]:
#嵌套dtype
selfStructType3 = [('x',[('a',np.float),('b',np.int)]),('y',np.int)]
selfArr3 = np.array([((1.1,2),5),((2.2,3),6)],dtype=selfStructType3)
selfArr3[0]['x']['a']

1.1

In [44]:
arr4 = np.arange(16).reshape(4,4)
np.sort(arr4[:,0])

array([ 0,  4,  8, 12])

In [46]:
arr5 = np.random.randn(3,5)
arr5[:,arr5[0].argsort()]

array([[-3.08770135e-01,  3.64855903e-04,  2.01781694e-01,
         9.71826109e-01,  1.55646276e+00],
       [ 6.85944215e-01,  8.13950287e-01, -2.86050003e-01,
        -1.82920314e+00,  1.10939526e+00],
       [ 2.04835288e-01, -4.18491179e-01,  1.13108880e+00,
        -2.73083917e-01, -5.91651414e-01]])

In [53]:
arr6 = np.array([0,1,7,12,15])
arr6.searchsorted([0,1,3])

array([[  0.,   0.,   0.,   0.],
       [  4.,   0.,   0.,  -4.],
       [  0.,   0.,   0., -16.],
       [  0.,   0.,   0.,   0.]])