In [1]:
import numpy as np


In [2]:
np.ones((10,5)).shape

(10, 5)

In [23]:
arr = np.arange(15).reshape((5,3),order = 'F')

In [ ]:
arr.ravel('F')

In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [18]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [30]:
arr3 = np.random.randn(1,5)

In [32]:
np.split(arr3,[1,2,3],axis=1)

[array([[0.89283378]]),
 array([[-0.21018224]]),
 array([[-0.33057199]]),
 array([[-0.31000341, -0.84278163]])]

In [43]:
arr4 = np.arange(6)
arr5 = arr4.reshape((3,2))
arr6 = np.random.randn(3,2)

In [44]:
np.vstack((arr5,arr6))

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.81696858,  0.73718992],
       [ 0.15325564, -1.79715369],
       [ 0.18528522,  1.45258024]])

In [45]:
#arr4为一维，arr5和arr6为二维，需要将arr4转换为２维
#上面解释是错的，在除０轴以外的广播较小数组的广播维必须为１
np.hstack((np.vstack((arr5,arr6)),arr4.reshape((6,-1))))

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.81696858,  0.73718992,  3.        ],
       [ 0.15325564, -1.79715369,  4.        ],
       [ 0.18528522,  1.45258024,  5.        ]])

In [46]:
arr4.reshape((6,-1)).shape

(6, 1)

In [4]:
arr = np.arange(3)
arr.repeat([2])

array([0, 0, 1, 1, 2, 2])

In [6]:
arr2  = np.random.randn(2,2)

In [8]:
arr2.repeat((2,2),axis=1)

array([[-0.26980052, -0.26980052,  0.24901947,  0.24901947],
       [ 0.03675499,  0.03675499, -0.38475084, -0.38475084]])

In [9]:
arr2.repeat((2,2),axis=0)

array([[-0.26980052,  0.24901947],
       [-0.26980052,  0.24901947],
       [ 0.03675499, -0.38475084],
       [ 0.03675499, -0.38475084]])

In [10]:
np.tile(arr2,[2,2])

array([[-0.26980052,  0.24901947, -0.26980052,  0.24901947],
       [ 0.03675499, -0.38475084,  0.03675499, -0.38475084],
       [-0.26980052,  0.24901947, -0.26980052,  0.24901947],
       [ 0.03675499, -0.38475084,  0.03675499, -0.38475084]])

In [18]:
arr3 = np.arange(10)*100
inds = [7,1,2,6]

In [22]:
arr4 = np.random.randn(2,4)
arr4.take([1,0],axis=0)

array([[ 0.39158796,  0.50365911,  2.2795848 , -0.44314684],
       [ 2.11930543, -0.46998462, -2.03016737, -0.09570549]])

In [25]:
arr5 = np.random.randn(1000,50)
indexs = np.random.permutation(1000)[:500]

In [28]:
%timeit arr5[indexs]

20.8 µs ± 5.67 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
%timeit arr5.take(indexs,axis =0)

10.9 µs ± 71.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
arr6 = np.random.randn(4,3)
arr6.mean(0)

array([-0.40116261,  1.21142467, -0.40510432])

In [34]:
demand = arr6 - arr6.mean(0)

In [36]:
demand.mean(0)

array([0.00000000e+00, 1.11022302e-16, 5.55111512e-17])

In [40]:
arr7 = np.arange(3)

In [47]:
arr6+arr7

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [49]:
arr8 = np.random.randn(4,3)
arr8_mean = arr8.mean(1)

In [53]:
arr8-arr8_mean.reshape(4,-1)

array([[-0.61101069, -0.62710907,  1.23811976],
       [ 0.68634113,  0.24437025, -0.93071137],
       [ 0.69440598, -0.13378692, -0.56061906],
       [-0.84117658,  0.62924003,  0.21193655]])

In [54]:
arr9 = np.zeros((4,4))

In [59]:
arr9[:,np.newaxis,:]

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [61]:
arr10 = np.random.normal(size=3)

In [77]:
arr11 = np.arange(60).reshape((3,4,5))
depth_means = arr11.mean(2)
demand = arr11 - depth_means[:,:,np.newaxis]

In [79]:
depth_means2 = arr11.mean(1)

(3, 5)

In [80]:
demand2 = arr11 - depth_means2[:,np.newaxis,:]

In [81]:
demand2.mean(1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])